import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Traduzioni base
const translations = {
  it: {
    // Auth
    'login': 'Accedi',
    'register': 'Registrati',
    'logout': 'Esci',
    'email': 'Email',
    'password': 'Password',
    'password_size_requirement': 'Minimo 6 caratteri',
    'name': 'Nome',
    'surname': 'Cognome',
    'phone': 'Telefono',
    'confirm_password': 'Conferma Password',
    'already_have_account': 'Hai già un account?',
    'dont_have_account': 'Non hai un account?',
    'login_here': 'Accedi qui',
    'register_here': 'Registrati qui',
    'forgot_password': 'Password dimenticata?',
    'personal_info': 'Informazioni personali',
    
    // Navigation
    'home': 'Home',
    'shop': 'Negozio',
    'cart': 'Carrello',
    'favorites': 'Preferiti',
    'profile': 'Profilo',
    'admin': 'Admin',
    'search': 'Cerca',
    'search_products': 'Cerca prodotti...',
    'menu': 'Menu',
    'close': 'Chiudi',
    'back': 'Indietro',
    
    // Product
    'my_products': 'I miei prodotti',
    'products': 'Prodotti',
    'no_products': 'Non hai ancora prodotti tra i preferiti.',
    'discover_products': 'Scopri i prodotti',
    'saved_products': 'prodotti salvati',
    'found_products': 'prodotti trovati',
    'price': 'Prezzo',
    'stock': 'Disponibilità',
    'in_stock': 'Disponibili',
    'out_of_stock': 'Esaurito',
    'add_to_cart': 'Aggiungi al carrello',
    'add_to_favorites': 'Aggiungi ai preferiti',
    'adding_to_favorites': 'Aggiungendo...',
    'remove_from_favorites': 'Rimuovi dai preferiti',
    'buy_now': 'Acquista ora',
    'product_details': 'Dettagli prodotto',
    'related_products': 'Prodotti correlati',
    'size': 'Taglia',
    'select_size': 'Seleziona taglia',
    'quantity': 'Quantità',
    'description': 'Descrizione',
    'category': 'Categoria',
    'code': 'Codice',
    
    // Categories
    'uomo': 'Uomo',
    'donna': 'Donna',
    'unisex': 'Unisex',
    't-shirt': 'T-shirt',
    'maglioni': 'Maglioni',
    'giacche': 'Giacche',
    'pantaloni': 'Pantaloni',
    'scarpe': 'Scarpe',
    'camicie': 'Camicie',
    'felpe': 'Felpe',
    'giubbotti': 'Giubbotti',
    'accessori': 'Accessori',
    'all_categories': 'Tutte le categorie',
    'all_genders': 'Tutti i generi',
    'gender': 'Genere',
    
    // Cart & Checkout
    'my_cart': 'Il mio carrello',
    'shopping_cart': 'Carrello acquisti',
    'cart_empty': 'Il tuo carrello è vuoto',
    'continue_shopping': 'Continua a fare shopping',
    'remove': 'Rimuovi',
    'update': 'Aggiorna',
    'subtotal': 'Subtotale',
    'total': 'Totale',
    'checkout': 'Procedi al pagamento',
    'shipping': 'Spedizione',
    'free': 'Gratuita',
    'billing_address': 'Indirizzo di fatturazione',
    'shipping_address': 'Indirizzo di spedizione',
    'payment_method': 'Metodo di pagamento',
    'place_order': 'Conferma ordine',
    'order_summary': 'Riepilogo ordine',
    'complete_order': 'Completa ordine',
    'test_order_info': '💳 Questo è un ordine di test - nessun pagamento reale verrà elaborato',
    'same_address': "L'indirizzo di spedizione è lo stesso dell'indirizzo di fatturazione",
    
    // User Profile
    'personal_area': 'Area personale',
    'my_orders': 'I miei ordini',
    'my_favorites': 'I miei preferiti',
    'account_settings': 'Impostazioni account',
    'edit_profile': 'Modifica profilo',
    'change_password': 'Cambia password',
    'order_history': 'Cronologia ordini',
    'order_date': 'Data ordine',
    'order_status': 'Stato ordine',
    'order_total': 'Totale ordine',
    
    // Admin
    'dashboard': 'Dashboard',
    'manage_products': 'Gestisci prodotti',
    'sales_report': 'Report vendite',
    'total_sales': 'Totale vendite',
    'no_sales': 'Nessuna vendita ancora effettuata.',
    'add_product': 'Aggiungi prodotto',
    'edit_product': 'Modifica prodotto',
    'delete_product': 'Elimina prodotto',
    'product_name': 'Nome prodotto',
    'product_image': 'Immagine prodotto',
    'upload_image': 'Carica immagine',
    'upload_new_product': 'Aggiungi nuovo prodotto',
    'save': 'Salva',
    'cancel': 'Annulla',
    'created': 'Creato',
    'updated': 'Aggiornato',
    'products_sold': 'Articoli Venduti',
    'total_revenue': 'Guadagni Totali',
    'total_products': 'Prodotti Caricati',
    'order': 'Ordine',
    'date': 'Data',
    'customer': 'Cliente',
    'actions': 'Azioni',
    'details': 'Dettagli',
    
    // General
    'welcome': 'Welcome',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'results_for': 'Results for',
    'no_results': 'No results found',
    'show_more': 'Show more',
    'show_less': 'Mostra meno',
    'view_all': 'Visualizza tutto',
    'new_arrivals': 'Nuovi arrivi',
    'featured_products': 'Prodotti in evidenza',
    'bestsellers': 'Più venduti',
    'sale': 'Saldo',
    'free_shipping': 'Spedizione gratuita',
    'customer_service': 'Servizio clienti',
    'contact_us': 'Contattaci',
    'about_us': 'Chi siamo',
    'terms_conditions': 'Termini e condizioni',
    'privacy_policy': 'Informativa privacy',
    'language': 'Lingua',
    'italian': 'Italiano',
    'english': 'Inglese',
    'modify': 'Modifica',
    'archive': 'Archivia',

    'footer_description': 'Il tuo negozio di abbigliamento di qualità. Scopri le nostre collezioni per uomo, donna e unisex.',
    'quick_links': 'Link Rapidi',
    'categories': 'Categorie', 
    'customer_support': 'Supporto Clienti',
    'legal_info': 'Informazioni Legali',
    'all_rights_reserved': 'Tutti i diritti riservati',
    'payment_methods': 'Metodi di pagamento',
    'cookie_policy': 'Policy Cookie',
    'size_guide': 'Guida alle taglie',
    'faq': 'Domande frequenti',
    'shippings': 'Spedizioni',
    'returns': 'Resi',

    'where_we_are': 'Dove ci troviamo',
    'our_location': 'La nostra sede',
    'visit_us': 'Vieni a trovarci nel nostro store',
    'address': 'Indirizzo',
    'genzano_address': 'Corso A. Gramsci, 61-69, 00045 Genzano di Roma (RM), Italia',
    'opening_hours': 'Orari di apertura',
    'monday_friday': 'Lunedì - Venerdì',
    'saturday': 'Sabato',
    'sunday': 'Domenica',
    'closed': 'Chiuso',
    'phone_number': 'Numero di telefono',
    'email_contact': 'Email di contatto',
    'store_hours_1': '9:00 - 13:00 / 16:30 - 19:30',
    'store_hours_2': '9:00 - 20:00',

  },
  en: {
    // Auth
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'password_size_requirement': 'Minimum 6 characters',
    'name': 'Name',
    'surname': 'Surname',
    'phone': 'Phone',
    'confirm_password': 'Confirm Password',
    'already_have_account': 'Already have an account?',
    'dont_have_account': "Don't have an account?",
    'login_here': 'Login here',
    'register_here': 'Register here',
    'forgot_password': 'Forgot password?',
    'personal_info': 'Personal information',
    
    // Navigation
    'home': 'Home',
    'shop': 'Shop',
    'cart': 'Cart',
    'favorites': 'Favorites',
    'profile': 'Profile',
    'admin': 'Admin',
    'search': 'Search',
    'search_products': 'Search products...',
    'menu': 'Menu',
    'close': 'Close',
    'back': 'Back',
    
    // Product
    'my_products': 'My products',
    'products': 'Products',
    'no_products': 'You have no products in your favorites yet.',
    'discover_products': 'Discover products',
    'saved_products': 'saved products',
    'found_products': 'products found',
    'price': 'Price',
    'stock': 'Stock',
    'in_stock': 'In Stock',
    'out_of_stock': 'Out of Stock',
    'add_to_cart': 'Add to cart',
    'add_to_favorites': 'Add to favorites',
    'adding_to_favorites': 'Adding...',
    'remove_from_favorites': 'Remove from favorites',
    'buy_now': 'Buy now',
    'product_details': 'Product details',
    'related_products': 'Related products',
    'size': 'Size',
    'select_size': 'Select size',
    'quantity': 'Quantity',
    'description': 'Description',
    'category': 'Category',
    'code': 'Code',
    
    // Categories
    'uomo': 'Men',
    'donna': 'Women',
    'unisex': 'Unisex',
    't-shirt': 'T-shirts',
    'maglioni': 'Sweaters',
    'giacche': 'Jackets',
    'pantaloni': 'Pants',
    'scarpe': 'Shoes',
    'camicie': 'Shirts',
    'felpe': 'Hoodies',
    'giubbotti': 'Coats',
    'accessori': 'Accessories',
    'all_categories': 'All categories',
    'all_genders': 'All genders',
    'gender': 'Gender',
    
    // Cart & Checkout
    "my_cart": 'My cart',
    'shopping_cart': 'Shopping cart',
    'cart_empty': 'Your cart is empty',
    'continue_shopping': 'Continue shopping',
    'remove': 'Remove',
    'update': 'Update',
    'subtotal': 'Subtotal',
    'total': 'Total',
    'checkout': 'Checkout',
    'shipping': 'Shipping',
    'free': 'Free',
    'billing_address': 'Billing address',
    'shipping_address': 'Shipping address',
    'payment_method': 'Payment method',
    'place_order': 'Place order',
    'order_summary': 'Order summary',
    'complete_order': 'Complete order',
    'same_address': 'Shipping address is the same as billing address',
    'test_order_info': '💳 This is a test order - no real payment will be processed',
    
    // User Profile
    'personal_area': 'Personal area',
    'my_orders': 'My orders',
    'my_favorites': 'My favorites',
    'account_settings': 'Account settings',
    'edit_profile': 'Edit profile',
    'change_password': 'Change password',
    'order_history': 'Order history',
    'order_date': 'Order date',
    'order_status': 'Order status',
    'order_total': 'Order total',
    
    // Admin
    'dashboard': 'Dashboard',
    'manage_products': 'Manage products',
    'sales_report': 'Sales report',
    'add_product': 'Add product',
    'edit_product': 'Edit product',
    'delete_product': 'Delete product',
    'product_name': 'Product name',
    'product_image': 'Product image',
    'upload_image': 'Upload image',
    'upload_new_product': 'Upload new product',
    'save': 'Save',
    'total_sales': 'Total sales',
    'no_sales': 'No sales made yet.',
    'cancel': 'Cancel',
    'created': 'Created',
    'updated': 'Updated',
    'products_sold': 'Products Sold',
    'total_revenue': 'Total Revenue',
    'total_products': 'Total Products',
    'date': 'Date',
    'customer': 'Customer',
    'actions': 'Actions',
    'details': 'Details',
    
    // General
    'welcome': 'Welcome',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'results_for': 'Results for',
    'no_results': 'No results found',
    'show_more': 'Show more',
    'show_less': 'Show less',
    'view_all': 'View all',
    'new_arrivals': 'New arrivals',
    'featured_products': 'Featured products',
    'bestsellers': 'Bestsellers',
    'sale': 'Sale',
    'free_shipping': 'Free shipping',
    'customer_service': 'Customer service',
    'contact_us': 'Contact us',
    'about_us': 'About us',
    'terms_conditions': 'Terms & conditions',
    'privacy_policy': 'Privacy policy',
    'language': 'Language',
    'italian': 'Italian',
    'english': 'English',
    'order': 'Order',
    'modify': 'Modify',
    'archive': 'Archive',

    'footer_description': 'Your fashion store for quality clothing. Discover our collections for men, women and unisex.',
    'quick_links': 'Quick Links',
    'categories': 'Categories',
    'customer_support': 'Customer Support', 
    'legal_info': 'Legal Information',
    'all_rights_reserved': 'All rights reserved',
    'payment_methods': 'Payment methods',
    'cookie_policy': 'Cookie Policy',
    'size_guide': 'Size guide',
    'faq': 'FAQ',
    'shippings': 'Shipping',
    'returns': 'Returns',

    'where_we_are': 'Where we are',
    'our_location': 'Our location', 
    'visit_us': 'Come visit us at our store',
    'address': 'Address',
    'genzano_address': 'Corso A. Gramsci, 61-69, 00045 Genzano di Roma (RM), Italy',
    'opening_hours': 'Opening hours',
    'monday_friday': 'Monday - Friday',
    'saturday': 'Saturday', 
    'sunday': 'Sunday',
    'closed': 'Closed',
    'phone_number': 'Phone number',
    'email_contact': 'Contact email',
    'store_hours_1': '9:00 AM - 13:00 PM / 4:30 PM - 7:30 PM',
    'store_hours_2': '9:00 AM - 8:00 PM',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.it] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};